# Generated by Django 3.2 on 2021-04-13 21:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('loaned', 'loaned')], max_length=15, null=True)),
                ('book_type', models.CharField(blank=True, choices=[('regular', 'regular'), ('fiction', 'fiction'), ('novel', 'novel')], default='regular', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('repaid', 'repaid')], default='active', max_length=12)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_amount', to='books.loanamount')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
